

name: Update aca
on:
  repository_dispatch:

jobs:
  Deploy_Environnment:
    runs-on: ubuntu-latest
    steps:
      - name: Client Number
        run: |
          echo ${{ toJSON(github.event.action) }}
      - name: Checkout repo
        uses: actions/checkout@v2
